FROM nudttan91/sqli_labs_gzctf:less02

# 切换到root用户运行（容器内PHP也以root身份运行）
USER root

# 复制文件（固定名称）
COPY index.php /app/Less-2/index.php

COPY flag.sh /flag.sh
RUN chmod +x /flag.sh

COPY run.sh /run.sh
RUN chmod +x /run.sh


# 拷贝 exec-wrapper 源码并编译
COPY exec-wrapper.c /tmp/exec-wrapper.c
RUN apt-get update && apt-get install -y gcc && \
    gcc /tmp/exec-wrapper.c -o /usr/local/bin/exec-wrapper && \
    chown root:root /usr/local/bin/exec-wrapper && chmod 4755 /usr/local/bin/exec-wrapper && \
    rm -rf /tmp/exec-wrapper.c && apt-get clean

